### ISSUE TITLE
Unknown object error

### ISSUE THREAD

**Issue by sowjanya143** [Moodstocks/inception-v3.torch#1]
torch/install/share/lua/5.1/torch/File.lua:294: unknown object

stack traceback:
torch/install/share/lua/5.1/torch/File.lua:294: in function 'readObject'
torch/install/share/lua/5.1/torch/File.lua:311: in function 'load'
example.lua:39: in main chunk
    [C]: in function 'dofile'
torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
    [C]: at 0x00406670

can someone suggest what can be done?

**Comment by deltheil** [comment]
- Did you complete steps 1 (TensorFlow dump filters) and 2 (Torch convert) successfully? (see README)
- What's the size of the Torch output binary (`inceptionv3.net`) you got? (it should typically be +180MB)
- Which backend (nn / cunn / cudnn) did you use?
