### ISSUE TITLE
error variable missing

### ISSUE THREAD

**Issue by jarmstrong2** [Moodstocks/inception-v3.torch#3]
luajit inceptionv3.lua -i dump -o inceptionv3.net -b cunn
Adding first convolutional layers:
conv: 3 -> 32, kernel (3x3), strides (2, 2), padding (0, 0)
luajit: inceptionv3.lua:69: attempt to index field 'running_var' (a nil value)
stack traceback:
    inceptionv3.lua:69: in function 'ConvBN'
    inceptionv3.lua:144: in main chunk
    [C]: at 0x00406670

**Comment by jarmstrong2** [comment]
nvm had to update nn

**Comment by tsaiJN** [comment]
Hello @jarmstrong2 , I'm now facing the same problem.
Could you share how you manage to solve it ? What do you mean by "nvm had to update nn" ?

**Comment by jarmstrong2** [comment]
basically, update torch and nn, i.e. (luarocks install nn)

**Comment by tsaiJN** [comment]
I did `luarocks install $package_name`
for torch, cutorch, hdf5, nn, cunn, cudnn, but the same error message still appear :(
