### ISSUE TITLE
luajit: inceptionv3.lua:107: attempt to call method 'setCountExcludePad' (a nil value)

### ISSUE THREAD

**Issue by tsaiJN** [Moodstocks/inception-v3.torch#5]
Hello,

I'm using cudnn backend to run `luajit inceptionv3.lua -i dump -o networks/inceptionv3.net -b cudnn`
and it gives the following error message:

Adding first convolutional layers:
conv: 3 -> 32, kernel (3x3), strides (2, 2), padding (0, 0)
conv_1: 32 -> 32, kernel (3x3), strides (1, 1), padding (0, 0)
conv_2: 32 -> 64, kernel (3x3), strides (1, 1), padding (1, 1)
pool(Max): (3x3), strides (2, 2), padding (0, 0)
conv_3: 64 -> 80, kernel (1x1), strides (1, 1), padding (0, 0)
conv_4: 80 -> 192, kernel (3x3), strides (1, 1), padding (0, 0)
pool_1(Max): (3x3), strides (2, 2), padding (0, 0)

Adding Inception 1:
mixed_conv: 192 -> 64, kernel (1x1), strides (1, 1), padding (0, 0)
mixed_tower_conv: 192 -> 48, kernel (1x1), strides (1, 1), padding (0, 0)
mixed_tower_conv_1: 48 -> 64, kernel (5x5), strides (1, 1), padding (2, 2)
mixed_tower_1_conv: 192 -> 64, kernel (1x1), strides (1, 1), padding (0, 0)
mixed_tower_1_conv_1: 64 -> 96, kernel (3x3), strides (1, 1), padding (1, 1)
mixed_tower_1_conv_2: 96 -> 96, kernel (3x3), strides (1, 1), padding (1, 1)
mixed_tower_2_pool(Avg): (3x3), strides (1, 1), padding (1, 1)
luajit: inceptionv3.lua:107: attempt to call method 'setCountExcludePad' (a nil value)
stack traceback:
    inceptionv3.lua:107: in function 'Pool'
    inceptionv3.lua:132: in function 'Tower'
    inceptionv3.lua:170: in main chunk
    [C]: at 0x00405be0

do anyone have any idea what's going on ?

**Comment by mdelakis** [comment]
You probably need to update your `nn` (at least) package to the latest version.

**Comment by tsaiJN** [comment]
How to update `nn` ?
I'm new to torch, I've tried
`luarocks install torch` and then `luarocks install nn`, but still get this error

how to check whether my package have successfully update to latest version?

**Comment by tsaiJN** [comment]
and inside the SpatialAveragePooling.lua, I saw these lines:
<img width="400" alt="screen shot 2016-04-25 at 6 15 40 pm" src="https://cloud.githubusercontent.com/assets/7351359/14780898/cdf76d28-0b11-11e6-8f69-429c9e107cc6.png">

doesn't that mean setCountExcludePad() shouldn't be nil ?

**Comment by mdelakis** [comment]
What do you get if you launch luajit from console with this command?

``` Bash
luajit -e "require 'nn'; print(nn.SpatialAveragePooling.setCountExcludePad)"
```

**Comment by tsaiJN** [comment]
sadly, nil was returned :(
